name: learn-github-actions
run-name: Deploy to ${{ inputs.deploy_target }} by ${{ github.actor }}
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: sparkfabrik/android-build-action@v1.3.4
        with:
          project-path: android
          output-path: my-app.apk
          browserstack-upload: true
          browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
          browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          ruby-version: "2.7.5"
          bundler-version: "2.3.26"
          fastlane-env: "debug"